"""Data models for the breadth expansion workflow.

Immutable dataclasses for audit reports, expansion proposals,
family directives, timeframe proposals, and workflow state.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


# ──────────────────────────────────────────────────────
# Phase A — Breadth Audit models
# ──────────────────────────────────────────────────────


@dataclass(frozen=True)
class StrategyRegimeExpectancy:
    """Expectancy for one strategy in one regime.

    Computed by cross-referencing fills with Hermes decisions.
    """

    strategy_id: str
    regime: str
    total_trades: int
    win_rate: float
    avg_pnl: float
    expectancy: float  # (win_rate * avg_win) - ((1-win_rate) * avg_loss)


@dataclass(frozen=True)
class ConfidenceBucket:
    """PnL distribution by confidence range.

    Buckets decisions into ranges (0.0-0.2, 0.2-0.4, etc.)
    and computes aggregate PnL stats per bucket.
    """

    bucket_label: str  # e.g. "0.0-0.2", "0.2-0.4", ...
    trade_count: int
    avg_pnl: float
    total_pnl: float
    win_rate: float


@dataclass(frozen=True)
class CorrelationCluster:
    """A group of mutually high-correlation symbols.

    Extracted via connected components (Union-Find) from
    high_correlation_pairs in the CorrelationMatrix.
    """

    cluster_id: int
    symbols: list[str]
    avg_internal_correlation: float


@dataclass(frozen=True)
class BreadthAuditReport:
    """Complete output of the breadth audit phase (Phase A).

    Contains strategy×regime expectancy, confidence bucketing,
    correlation structure, and auto-generated recommendations.
    """

    # Strategy × Regime analysis
    strategy_regime_expectancy: list[StrategyRegimeExpectancy]
    # Confidence analysis
    confidence_buckets: list[ConfidenceBucket]
    # Correlation structure
    correlation_clusters: list[CorrelationCluster]
    high_correlation_pairs: list[tuple[str, str, float]]
    correlation_summary: dict  # pairs, mean, max, high_pairs
    # Current universe
    current_symbols: list[str]
    current_scaling_profile: str
    # Recommendations (auto-generated)
    positive_edge_strategies: list[str]  # strategies with positive expectancy
    diversifying_symbols: list[str]  # symbols NOT in any high-correlation cluster
    redundant_symbols: list[str]  # symbols in oversized clusters
    # Metadata
    computed_at: str
    data_points_used: int


# ──────────────────────────────────────────────────────
# Phase B — Symbol Expansion models
# ──────────────────────────────────────────────────────


@dataclass(frozen=True)
class ExpansionCandidate:
    """A candidate symbol for universe expansion.

    Includes correlation stats relative to the current universe.
    """

    symbol: str
    pool: str  # Which pool it comes from
    bucket: str  # Asset class bucket
    avg_correlation_with_existing: float  # Mean |r| vs current universe
    max_correlation_with_existing: float  # Max |r| vs any current symbol
    is_low_correlation: bool  # True if max |r| < 0.5


@dataclass(frozen=True)
class RiskImpact:
    """Simulated risk impact of adding a symbol."""

    symbol: str
    current_portfolio_risk: float
    projected_portfolio_risk: float
    risk_change: float
    correlation_adjusted_change: float  # After correlation discounting
    within_budget: bool


@dataclass(frozen=True)
class SymbolExpansionProposal:
    """Proposal to add symbols to the universe.

    Generated by SymbolExpander, presented for HITL approval.
    """

    proposal_id: str
    audit_id: int  # Links to breadth_audits table
    current_symbols: list[str]
    proposed_additions: list[ExpansionCandidate]
    risk_impacts: list[RiskImpact]
    scaling_profile: str
    total_symbols_after: int
    within_profile_limit: bool
    correlation_diversity_score: float  # 0-1, higher = more diversifying
    status: str = "PENDING"  # PENDING | APPROVED | REJECTED | IGNORED
    created_at: str = ""
    decided_at: str | None = None
    decision_reason: str | None = None


# ──────────────────────────────────────────────────────
# Phase C — Strategy Family models
# ──────────────────────────────────────────────────────


@dataclass(frozen=True)
class FamilyDirective:
    """Record of family assignment for a symbol.

    Tracks which families were assigned, which regime was active,
    and which family Hermes actually selected.
    """

    symbol: str
    bucket: str
    assigned_families: list[str]
    regime_used: str | None  # Which regime was active during verification
    family_used: str | None  # Which family Hermes actually selected
    correct_switch: bool | None  # True if family matched regime expectation
    timestamp: str = ""


# ──────────────────────────────────────────────────────
# Phase D — Timeframe models
# ──────────────────────────────────────────────────────


@dataclass(frozen=True)
class TimeframeProposal:
    """Proposal to enable additional timeframe.

    Only generated when gating conditions pass (MEDIUM/LARGE profile,
    stable breadth, positive expectancy on primary timeframe).
    """

    proposal_id: str
    current_timeframe: str
    proposed_timeframe: str
    symbols_affected: list[str]
    marginal_opportunity_increase: float  # Expected % more opportunities
    htf_ltf_alignment_score: float  # 0-1, how well timeframes agree
    risk_impact_summary: str
    status: str = "PENDING"
    created_at: str = ""
    decided_at: str | None = None


# ──────────────────────────────────────────────────────
# Workflow models
# ──────────────────────────────────────────────────────


class WorkflowPhase(Enum):
    """Current phase of the breadth expansion workflow."""

    IDLE = "IDLE"
    AUDIT = "AUDIT"  # Phase A
    EXPANSION = "EXPANSION"  # Phase B
    FAMILY = "FAMILY"  # Phase C
    TIMEFRAME = "TIMEFRAME"  # Phase D
    AWAITING_HIL = "AWAITING_HIL"
    COMPLETE = "COMPLETE"


@dataclass
class BreadthWorkflowState:
    """Current state of the breadth expansion workflow.

    Mutable — updated as the workflow progresses through phases.
    """

    phase: WorkflowPhase = WorkflowPhase.IDLE
    audit_report: BreadthAuditReport | None = None
    expansion_proposal: SymbolExpansionProposal | None = None
    family_directives: list[FamilyDirective] = field(default_factory=list)
    timeframe_proposal: TimeframeProposal | None = None
    history: list[dict] = field(default_factory=list)  # Audit trail
    started_at: str = ""
    last_updated: str = ""
